In [17]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [18]:
df = pd.read_csv("/content/drive/MyDrive/fiscal.csv")

In [12]:
df

,Company,Fiscal Year,Total Revenue,Net Income,Total Assets,Total Liability,Cash Flow From Operations
0,Microsoft,2021,168088,61271,333779,191791,76740
1,Microsoft,2022,198270,72738,364840,198298,89035
2,Microsoft,2023,211915,72361,411976,205753,87582
3,Tesla,2021,53823,5644,62131,30548,11497
4,Tesla,2022,81462,12587,82338,36440,14724
5,Tesla,2023,96773,14974,106618,43009,13256
6,Apple,2021,365817,94680,351002,287912,104038
7,Apple,2022,394328,99803,352755,302083,122151
8,Apple,2023,383285,96995,352583,290437,110543

In [20]:
# Calculate Revenue Growth (%) and Net Income Growth (%)
df['Revenue Growth (%)'] = df.groupby(['Company '])['Total Revenue'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby(['Company '])['Net Income'].pct_change() * 100

# Create a new DataFrame to display growth metrics in tabular format
growth_table = df[['Company ', 'Fiscal Year', 'Revenue Growth (%)', 'Net Income Growth (%)']].copy()
growth_table.fillna(0, inplace=True)  # Replace NaN with 0 for better readability
print("Growth Metrics Table:")
print(growth_table.to_string(index=False))

Growth Metrics Table:
 Company   Fiscal Year  Revenue Growth (%)  Net Income Growth (%)
Microsoft         2021            0.000000               0.000000
Microsoft         2022           17.956071              18.715216
Microsoft         2023            6.882030              -0.518299
    Tesla         2021            0.000000               0.000000
    Tesla         2022           51.351653             123.015592
    Tesla         2023           18.795267              18.964010
    Apple         2021            0.000000               0.000000
    Apple         2022            7.793788               5.410858
    Apple         2023           -2.800461              -2.813543

In [21]:
# prompt: create a simple chat bot

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/fiscal.csv")

df

# Calculate Revenue Growth (%) and Net Income Growth (%)
df['Revenue Growth (%)'] = df.groupby(['Company '])['Total Revenue'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby(['Company '])['Net Income'].pct_change() * 100

# Create a new DataFrame to display growth metrics in tabular format
growth_table = df[['Company ', 'Fiscal Year', 'Revenue Growth (%)', 'Net Income Growth (%)']].copy()
growth_table.fillna(0, inplace=True)  # Replace NaN with 0 for better readability

# Simple chatbot functionality
def chatbot():
    print("Welcome to the Financial Growth Chatbot!")
    while True:
        user_input = input("Ask me about revenue or net income growth (or type 'exit'): ").lower()
        if user_input == 'exit':
            break
        elif "revenue growth" in user_input:
            company = input("For which company? ")
            year = input("For which fiscal year? ")
            try:
              growth = growth_table[(growth_table['Company '] == company) & (growth_table['Fiscal Year'] == int(year))]['Revenue Growth (%)'].iloc[0]
              print(f"The revenue growth for {company} in {year} was {growth:.2f}%.")
            except (IndexError, ValueError):
                print("Data not found for the specified company and year.")

        elif "net income growth" in user_input:
            company = input("For which company? ")
            year = input("For which fiscal year? ")
            try:
              growth = growth_table[(growth_table['Company '] == company) & (growth_table['Fiscal Year'] == int(year))]['Net Income Growth (%)'].iloc[0]
              print(f"The net income growth for {company} in {year} was {growth:.2f}%.")
            except (IndexError, ValueError):
                print("Data not found for the specified company and year.")
        else:
            print("I'm sorry, I don't understand your question.")

chatbot()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Welcome to the Financial Growth Chatbot!
Ask me about revenue or net income growth (or type 'exit'): revenue
I'm sorry, I don't understand your question.
Ask me about revenue or net income growth (or type 'exit'): revenue grouth
I'm sorry, I don't understand your question.
Ask me about revenue or net income growth (or type 'exit'): revenue growth
For which company? Apple
For which fiscal year? 2021
The revenue growth for Apple in 2021 was 0.00%.
Ask me about revenue or net income growth (or type 'exit'): revenue growth
For which company? Apple
For which fiscal year? 2023
The revenue growth for Apple in 2023 was -2.80%.
Ask me about revenue or net income growth (or type 'exit'): exit